package com.zqm.dao.entity;

import java.util.Date;

public class TCommentInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment_info.id
     *
     * @mbg.generated Tue Aug 06 09:02:32 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment_info.new_id
     *
     * @mbg.generated Tue Aug 06 09:02:32 CST 2019
     */
    private String newId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment_info.user_name
     *
     * @mbg.generated Tue Aug 06 09:02:32 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment_info.user_tel
     *
     * @mbg.generated Tue Aug 06 09:02:32 CST 2019
     */
    private String userTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment_info.read_count
     *
     * @mbg.generated Tue Aug 06 09:02:32 CST 2019
     */
    private Integer readCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment_info.is_delete
     *
     * @mbg.generated Tue Aug 06 09:02:32 CST 2019
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment_info.create_time
     *
     * @mbg.generated Tue Aug 06 09:02:32 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment_info.update_time
     *
     * @mbg.generated Tue Aug 06 09:02:32 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment_info.content
     *
     * @mbg.generated Tue Aug 06 09:02:32 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment_info.id
     *
     * @return the value of t_comment_info.id
     *
     * @mbg.generated Tue Aug 06 09:02:32 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment_info.id
     *
     * @param id the value for t_comment_info.id
     *
     * @mbg.generated Tue Aug 06 09:02:32 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment_info.new_id
     *
     * @return the value of t_comment_info.new_id
     *
     * @mbg.generated Tue Aug 06 09:02:32 CST 2019
     */
    public String getNewId() {
        return newId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment_info.new_id
     *
     * @param newId the value for t_comment_info.new_id
     *
     * @mbg.generated Tue Aug 06 09:02:32 CST 2019
     */
    public void setNewId(String newId) {
        this.newId = newId == null ? null : newId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment_info.user_name
     *
     * @return the value of t_comment_info.user_name
     *
     * @mbg.generated Tue Aug 06 09:02:32 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment_info.user_name
     *
     * @param userName the value for t_comment_info.user_name
     *
     * @mbg.generated Tue Aug 06 09:02:32 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment_info.user_tel
     *
     * @return the value of t_comment_info.user_tel
     *
     * @mbg.generated Tue Aug 06 09:02:32 CST 2019
     */
    public String getUserTel() {
        return userTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment_info.user_tel
     *
     * @param userTel the value for t_comment_info.user_tel
     *
     * @mbg.generated Tue Aug 06 09:02:32 CST 2019
     */
    public void setUserTel(String userTel) {
        this.userTel = userTel == null ? null : userTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment_info.read_count
     *
     * @return the value of t_comment_info.read_count
     *
     * @mbg.generated Tue Aug 06 09:02:32 CST 2019
     */
    public Integer getReadCount() {
        return readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment_info.read_count
     *
     * @param readCount the value for t_comment_info.read_count
     *
     * @mbg.generated Tue Aug 06 09:02:32 CST 2019
     */
    public void setReadCount(Integer readCount) {
        this.readCount = readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment_info.is_delete
     *
     * @return the value of t_comment_info.is_delete
     *
     * @mbg.generated Tue Aug 06 09:02:32 CST 2019
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment_info.is_delete
     *
     * @param isDelete the value for t_comment_info.is_delete
     *
     * @mbg.generated Tue Aug 06 09:02:32 CST 2019
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment_info.create_time
     *
     * @return the value of t_comment_info.create_time
     *
     * @mbg.generated Tue Aug 06 09:02:32 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment_info.create_time
     *
     * @param createTime the value for t_comment_info.create_time
     *
     * @mbg.generated Tue Aug 06 09:02:32 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment_info.update_time
     *
     * @return the value of t_comment_info.update_time
     *
     * @mbg.generated Tue Aug 06 09:02:32 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment_info.update_time
     *
     * @param updateTime the value for t_comment_info.update_time
     *
     * @mbg.generated Tue Aug 06 09:02:32 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment_info.content
     *
     * @return the value of t_comment_info.content
     *
     * @mbg.generated Tue Aug 06 09:02:32 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment_info.content
     *
     * @param content the value for t_comment_info.content
     *
     * @mbg.generated Tue Aug 06 09:02:32 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}