package com.zqm.dao.entity;

import java.util.ArrayList;
import java.util.List;

public class THistoryPValueExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_history_p_value
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_history_p_value
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_history_p_value
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_p_value
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    public THistoryPValueExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_p_value
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_p_value
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_p_value
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_p_value
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_p_value
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_p_value
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_p_value
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_p_value
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_p_value
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history_p_value
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_history_p_value
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTuniuIdIsNull() {
            addCriterion("tuniu_id is null");
            return (Criteria) this;
        }

        public Criteria andTuniuIdIsNotNull() {
            addCriterion("tuniu_id is not null");
            return (Criteria) this;
        }

        public Criteria andTuniuIdEqualTo(Integer value) {
            addCriterion("tuniu_id =", value, "tuniuId");
            return (Criteria) this;
        }

        public Criteria andTuniuIdNotEqualTo(Integer value) {
            addCriterion("tuniu_id <>", value, "tuniuId");
            return (Criteria) this;
        }

        public Criteria andTuniuIdGreaterThan(Integer value) {
            addCriterion("tuniu_id >", value, "tuniuId");
            return (Criteria) this;
        }

        public Criteria andTuniuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("tuniu_id >=", value, "tuniuId");
            return (Criteria) this;
        }

        public Criteria andTuniuIdLessThan(Integer value) {
            addCriterion("tuniu_id <", value, "tuniuId");
            return (Criteria) this;
        }

        public Criteria andTuniuIdLessThanOrEqualTo(Integer value) {
            addCriterion("tuniu_id <=", value, "tuniuId");
            return (Criteria) this;
        }

        public Criteria andTuniuIdIn(List<Integer> values) {
            addCriterion("tuniu_id in", values, "tuniuId");
            return (Criteria) this;
        }

        public Criteria andTuniuIdNotIn(List<Integer> values) {
            addCriterion("tuniu_id not in", values, "tuniuId");
            return (Criteria) this;
        }

        public Criteria andTuniuIdBetween(Integer value1, Integer value2) {
            addCriterion("tuniu_id between", value1, value2, "tuniuId");
            return (Criteria) this;
        }

        public Criteria andTuniuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("tuniu_id not between", value1, value2, "tuniuId");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueIsNull() {
            addCriterion("history_p_value is null");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueIsNotNull() {
            addCriterion("history_p_value is not null");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueEqualTo(String value) {
            addCriterion("history_p_value =", value, "historyPValue");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueNotEqualTo(String value) {
            addCriterion("history_p_value <>", value, "historyPValue");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueGreaterThan(String value) {
            addCriterion("history_p_value >", value, "historyPValue");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueGreaterThanOrEqualTo(String value) {
            addCriterion("history_p_value >=", value, "historyPValue");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueLessThan(String value) {
            addCriterion("history_p_value <", value, "historyPValue");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueLessThanOrEqualTo(String value) {
            addCriterion("history_p_value <=", value, "historyPValue");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueLike(String value) {
            addCriterion("history_p_value like", value, "historyPValue");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueNotLike(String value) {
            addCriterion("history_p_value not like", value, "historyPValue");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueIn(List<String> values) {
            addCriterion("history_p_value in", values, "historyPValue");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueNotIn(List<String> values) {
            addCriterion("history_p_value not in", values, "historyPValue");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueBetween(String value1, String value2) {
            addCriterion("history_p_value between", value1, value2, "historyPValue");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueNotBetween(String value1, String value2) {
            addCriterion("history_p_value not between", value1, value2, "historyPValue");
            return (Criteria) this;
        }

        public Criteria andIdSIsNull() {
            addCriterion("id_s is null");
            return (Criteria) this;
        }

        public Criteria andIdSIsNotNull() {
            addCriterion("id_s is not null");
            return (Criteria) this;
        }

        public Criteria andIdSEqualTo(Integer value) {
            addCriterion("id_s =", value, "idS");
            return (Criteria) this;
        }

        public Criteria andIdSNotEqualTo(Integer value) {
            addCriterion("id_s <>", value, "idS");
            return (Criteria) this;
        }

        public Criteria andIdSGreaterThan(Integer value) {
            addCriterion("id_s >", value, "idS");
            return (Criteria) this;
        }

        public Criteria andIdSGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_s >=", value, "idS");
            return (Criteria) this;
        }

        public Criteria andIdSLessThan(Integer value) {
            addCriterion("id_s <", value, "idS");
            return (Criteria) this;
        }

        public Criteria andIdSLessThanOrEqualTo(Integer value) {
            addCriterion("id_s <=", value, "idS");
            return (Criteria) this;
        }

        public Criteria andIdSIn(List<Integer> values) {
            addCriterion("id_s in", values, "idS");
            return (Criteria) this;
        }

        public Criteria andIdSNotIn(List<Integer> values) {
            addCriterion("id_s not in", values, "idS");
            return (Criteria) this;
        }

        public Criteria andIdSBetween(Integer value1, Integer value2) {
            addCriterion("id_s between", value1, value2, "idS");
            return (Criteria) this;
        }

        public Criteria andIdSNotBetween(Integer value1, Integer value2) {
            addCriterion("id_s not between", value1, value2, "idS");
            return (Criteria) this;
        }

        public Criteria andTuniuIdSIsNull() {
            addCriterion("tuniu_id_s is null");
            return (Criteria) this;
        }

        public Criteria andTuniuIdSIsNotNull() {
            addCriterion("tuniu_id_s is not null");
            return (Criteria) this;
        }

        public Criteria andTuniuIdSEqualTo(Integer value) {
            addCriterion("tuniu_id_s =", value, "tuniuIdS");
            return (Criteria) this;
        }

        public Criteria andTuniuIdSNotEqualTo(Integer value) {
            addCriterion("tuniu_id_s <>", value, "tuniuIdS");
            return (Criteria) this;
        }

        public Criteria andTuniuIdSGreaterThan(Integer value) {
            addCriterion("tuniu_id_s >", value, "tuniuIdS");
            return (Criteria) this;
        }

        public Criteria andTuniuIdSGreaterThanOrEqualTo(Integer value) {
            addCriterion("tuniu_id_s >=", value, "tuniuIdS");
            return (Criteria) this;
        }

        public Criteria andTuniuIdSLessThan(Integer value) {
            addCriterion("tuniu_id_s <", value, "tuniuIdS");
            return (Criteria) this;
        }

        public Criteria andTuniuIdSLessThanOrEqualTo(Integer value) {
            addCriterion("tuniu_id_s <=", value, "tuniuIdS");
            return (Criteria) this;
        }

        public Criteria andTuniuIdSIn(List<Integer> values) {
            addCriterion("tuniu_id_s in", values, "tuniuIdS");
            return (Criteria) this;
        }

        public Criteria andTuniuIdSNotIn(List<Integer> values) {
            addCriterion("tuniu_id_s not in", values, "tuniuIdS");
            return (Criteria) this;
        }

        public Criteria andTuniuIdSBetween(Integer value1, Integer value2) {
            addCriterion("tuniu_id_s between", value1, value2, "tuniuIdS");
            return (Criteria) this;
        }

        public Criteria andTuniuIdSNotBetween(Integer value1, Integer value2) {
            addCriterion("tuniu_id_s not between", value1, value2, "tuniuIdS");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueSIsNull() {
            addCriterion("history_p_value_s is null");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueSIsNotNull() {
            addCriterion("history_p_value_s is not null");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueSEqualTo(String value) {
            addCriterion("history_p_value_s =", value, "historyPValueS");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueSNotEqualTo(String value) {
            addCriterion("history_p_value_s <>", value, "historyPValueS");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueSGreaterThan(String value) {
            addCriterion("history_p_value_s >", value, "historyPValueS");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueSGreaterThanOrEqualTo(String value) {
            addCriterion("history_p_value_s >=", value, "historyPValueS");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueSLessThan(String value) {
            addCriterion("history_p_value_s <", value, "historyPValueS");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueSLessThanOrEqualTo(String value) {
            addCriterion("history_p_value_s <=", value, "historyPValueS");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueSLike(String value) {
            addCriterion("history_p_value_s like", value, "historyPValueS");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueSNotLike(String value) {
            addCriterion("history_p_value_s not like", value, "historyPValueS");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueSIn(List<String> values) {
            addCriterion("history_p_value_s in", values, "historyPValueS");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueSNotIn(List<String> values) {
            addCriterion("history_p_value_s not in", values, "historyPValueS");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueSBetween(String value1, String value2) {
            addCriterion("history_p_value_s between", value1, value2, "historyPValueS");
            return (Criteria) this;
        }

        public Criteria andHistoryPValueSNotBetween(String value1, String value2) {
            addCriterion("history_p_value_s not between", value1, value2, "historyPValueS");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_history_p_value
     *
     * @mbg.generated do_not_delete_during_merge Mon Jul 29 11:53:44 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_history_p_value
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}