package com.zqm.dao.entity;

public class THistoryPValue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_p_value.id
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_p_value.tuniu_id
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    private Integer tuniuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_p_value.history_p_value
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    private String historyPValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_p_value.id_s
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    private Integer idS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_p_value.tuniu_id_s
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    private Integer tuniuIdS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history_p_value.history_p_value_s
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    private String historyPValueS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_p_value.id
     *
     * @return the value of t_history_p_value.id
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_p_value.id
     *
     * @param id the value for t_history_p_value.id
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_p_value.tuniu_id
     *
     * @return the value of t_history_p_value.tuniu_id
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    public Integer getTuniuId() {
        return tuniuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_p_value.tuniu_id
     *
     * @param tuniuId the value for t_history_p_value.tuniu_id
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    public void setTuniuId(Integer tuniuId) {
        this.tuniuId = tuniuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_p_value.history_p_value
     *
     * @return the value of t_history_p_value.history_p_value
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    public String getHistoryPValue() {
        return historyPValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_p_value.history_p_value
     *
     * @param historyPValue the value for t_history_p_value.history_p_value
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    public void setHistoryPValue(String historyPValue) {
        this.historyPValue = historyPValue == null ? null : historyPValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_p_value.id_s
     *
     * @return the value of t_history_p_value.id_s
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    public Integer getIdS() {
        return idS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_p_value.id_s
     *
     * @param idS the value for t_history_p_value.id_s
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    public void setIdS(Integer idS) {
        this.idS = idS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_p_value.tuniu_id_s
     *
     * @return the value of t_history_p_value.tuniu_id_s
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    public Integer getTuniuIdS() {
        return tuniuIdS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_p_value.tuniu_id_s
     *
     * @param tuniuIdS the value for t_history_p_value.tuniu_id_s
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    public void setTuniuIdS(Integer tuniuIdS) {
        this.tuniuIdS = tuniuIdS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history_p_value.history_p_value_s
     *
     * @return the value of t_history_p_value.history_p_value_s
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    public String getHistoryPValueS() {
        return historyPValueS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history_p_value.history_p_value_s
     *
     * @param historyPValueS the value for t_history_p_value.history_p_value_s
     *
     * @mbg.generated Mon Jul 29 11:53:44 CST 2019
     */
    public void setHistoryPValueS(String historyPValueS) {
        this.historyPValueS = historyPValueS == null ? null : historyPValueS.trim();
    }
}