package com.zqm.dao.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class TUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.id
     *
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.tel
     *
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.password
     *
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.name
     *
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.image
     *
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.age
     *
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    private String age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.birthday
     *
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.sex
     *
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    private Byte sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.address
     *
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.label
     *
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.is_delete
     *
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.create_time
     *
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",locale = "zh",timezone = "GMT+8")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.update_time
     *
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.id
     *
     * @return the value of t_user_info.id
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.id
     *
     * @param id the value for t_user_info.id
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.tel
     *
     * @return the value of t_user_info.tel
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.tel
     *
     * @param tel the value for t_user_info.tel
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.password
     *
     * @return the value of t_user_info.password
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.password
     *
     * @param password the value for t_user_info.password
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.name
     *
     * @return the value of t_user_info.name
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.name
     *
     * @param name the value for t_user_info.name
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.image
     *
     * @return the value of t_user_info.image
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.image
     *
     * @param image the value for t_user_info.image
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.age
     *
     * @return the value of t_user_info.age
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.age
     *
     * @param age the value for t_user_info.age
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.birthday
     *
     * @return the value of t_user_info.birthday
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.birthday
     *
     * @param birthday the value for t_user_info.birthday
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.sex
     *
     * @return the value of t_user_info.sex
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.sex
     *
     * @param sex the value for t_user_info.sex
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.address
     *
     * @return the value of t_user_info.address
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.address
     *
     * @param address the value for t_user_info.address
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.label
     *
     * @return the value of t_user_info.label
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.label
     *
     * @param label the value for t_user_info.label
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.is_delete
     *
     * @return the value of t_user_info.is_delete
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.is_delete
     *
     * @param isDelete the value for t_user_info.is_delete
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.create_time
     *
     * @return the value of t_user_info.create_time
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.create_time
     *
     * @param createTime the value for t_user_info.create_time
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.update_time
     *
     * @return the value of t_user_info.update_time
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.update_time
     *
     * @param updateTime the value for t_user_info.update_time
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}