package com.zqm.dao.entity;

import java.util.Date;

public class TNewsInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_info.id
     *
     * @mbg.generated Mon Jul 22 16:30:15 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_info.name
     *
     * @mbg.generated Mon Jul 22 16:30:15 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_info.label
     *
     * @mbg.generated Mon Jul 22 16:30:15 CST 2019
     */
    private String label;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_info.read_count
     *
     * @mbg.generated Mon Jul 22 16:30:15 CST 2019
     */
    private Integer readCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_info.is_delete
     *
     * @mbg.generated Mon Jul 22 16:30:15 CST 2019
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_info.is_publish
     *
     * @mbg.generated Mon Jul 22 16:30:15 CST 2019
     */
    private Boolean isPublish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_info.create_time
     *
     * @mbg.generated Mon Jul 22 16:30:15 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_info.update_time
     *
     * @mbg.generated Mon Jul 22 16:30:15 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news_info.content
     *
     * @mbg.generated Mon Jul 22 16:30:15 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_info.id
     *
     * @return the value of t_news_info.id
     *
     * @mbg.generated Mon Jul 22 16:30:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_info.id
     *
     * @param id the value for t_news_info.id
     *
     * @mbg.generated Mon Jul 22 16:30:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_info.name
     *
     * @return the value of t_news_info.name
     *
     * @mbg.generated Mon Jul 22 16:30:15 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_info.name
     *
     * @param name the value for t_news_info.name
     *
     * @mbg.generated Mon Jul 22 16:30:15 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_info.label
     *
     * @return the value of t_news_info.label
     *
     * @mbg.generated Mon Jul 22 16:30:15 CST 2019
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_info.label
     *
     * @param label the value for t_news_info.label
     *
     * @mbg.generated Mon Jul 22 16:30:15 CST 2019
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_info.read_count
     *
     * @return the value of t_news_info.read_count
     *
     * @mbg.generated Mon Jul 22 16:30:15 CST 2019
     */
    public Integer getReadCount() {
        return readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_info.read_count
     *
     * @param readCount the value for t_news_info.read_count
     *
     * @mbg.generated Mon Jul 22 16:30:15 CST 2019
     */
    public void setReadCount(Integer readCount) {
        this.readCount = readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_info.is_delete
     *
     * @return the value of t_news_info.is_delete
     *
     * @mbg.generated Mon Jul 22 16:30:15 CST 2019
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_info.is_delete
     *
     * @param isDelete the value for t_news_info.is_delete
     *
     * @mbg.generated Mon Jul 22 16:30:15 CST 2019
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_info.is_publish
     *
     * @return the value of t_news_info.is_publish
     *
     * @mbg.generated Mon Jul 22 16:30:15 CST 2019
     */
    public Boolean getIsPublish() {
        return isPublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_info.is_publish
     *
     * @param isPublish the value for t_news_info.is_publish
     *
     * @mbg.generated Mon Jul 22 16:30:15 CST 2019
     */
    public void setIsPublish(Boolean isPublish) {
        this.isPublish = isPublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_info.create_time
     *
     * @return the value of t_news_info.create_time
     *
     * @mbg.generated Mon Jul 22 16:30:15 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_info.create_time
     *
     * @param createTime the value for t_news_info.create_time
     *
     * @mbg.generated Mon Jul 22 16:30:15 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_info.update_time
     *
     * @return the value of t_news_info.update_time
     *
     * @mbg.generated Mon Jul 22 16:30:15 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_info.update_time
     *
     * @param updateTime the value for t_news_info.update_time
     *
     * @mbg.generated Mon Jul 22 16:30:15 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news_info.content
     *
     * @return the value of t_news_info.content
     *
     * @mbg.generated Mon Jul 22 16:30:15 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news_info.content
     *
     * @param content the value for t_news_info.content
     *
     * @mbg.generated Mon Jul 22 16:30:15 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}