package com.zqm.dao.mapper;

import com.zqm.dao.entity.TNewsInfo;
import com.zqm.dao.entity.TNewsInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TNewsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_info
     *
     * @mbg.generated Mon Jul 29 11:53:16 CST 2019
     */
    long countByExample(TNewsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_info
     *
     * @mbg.generated Mon Jul 29 11:53:16 CST 2019
     */
    int deleteByExample(TNewsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_info
     *
     * @mbg.generated Mon Jul 29 11:53:16 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_info
     *
     * @mbg.generated Mon Jul 29 11:53:16 CST 2019
     */
    int insert(TNewsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_info
     *
     * @mbg.generated Mon Jul 29 11:53:16 CST 2019
     */
    int insertSelective(TNewsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_info
     *
     * @mbg.generated Mon Jul 29 11:53:16 CST 2019
     */
    List<TNewsInfo> selectByExampleWithBLOBsWithRowbounds(TNewsInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_info
     *
     * @mbg.generated Mon Jul 29 11:53:16 CST 2019
     */
    List<TNewsInfo> selectByExampleWithBLOBs(TNewsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_info
     *
     * @mbg.generated Mon Jul 29 11:53:16 CST 2019
     */
    List<TNewsInfo> selectByExampleWithRowbounds(TNewsInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_info
     *
     * @mbg.generated Mon Jul 29 11:53:16 CST 2019
     */
    List<TNewsInfo> selectByExample(TNewsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_info
     *
     * @mbg.generated Mon Jul 29 11:53:16 CST 2019
     */
    TNewsInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_info
     *
     * @mbg.generated Mon Jul 29 11:53:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") TNewsInfo record, @Param("example") TNewsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_info
     *
     * @mbg.generated Mon Jul 29 11:53:16 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") TNewsInfo record, @Param("example") TNewsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_info
     *
     * @mbg.generated Mon Jul 29 11:53:16 CST 2019
     */
    int updateByExample(@Param("record") TNewsInfo record, @Param("example") TNewsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_info
     *
     * @mbg.generated Mon Jul 29 11:53:16 CST 2019
     */
    int updateByPrimaryKeySelective(TNewsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_info
     *
     * @mbg.generated Mon Jul 29 11:53:16 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(TNewsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news_info
     *
     * @mbg.generated Mon Jul 29 11:53:16 CST 2019
     */
    int updateByPrimaryKey(TNewsInfo record);
}