package com.zqm.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.zqm.dao.entity.TUserInfo;
import com.zqm.dao.entity.TUserInfoExample;

public interface TUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    long countByExample(TUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    int deleteByExample(TUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    int insert(TUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    int insertSelective(TUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    List<TUserInfo> selectByExampleWithRowbounds(TUserInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    List<TUserInfo> selectByExample(TUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    TUserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") TUserInfo record, @Param("example") TUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    int updateByExample(@Param("record") TUserInfo record, @Param("example") TUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    int updateByPrimaryKeySelective(TUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbg.generated Mon Jul 29 11:53:04 CST 2019
     */
    int updateByPrimaryKey(TUserInfo record);
}